from:approve-config/application/application-native.yml
spring:

  datasource:
    url: jdbc:mysql://localhost:3306/attend?allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  rabbitmq:
    host: localhost
    username: springcloud
    password: 123456
#    virtual-host: /work-office

#  cloud:
#    stream:
#      binders:
#        rabbit1:
#          type: rabbit
#      bindings:
#        rabbit1:
#          output:
#            destination: trace

logging:
  path: log

#jedis:
#  servers:

#message:
#  send:
#    switch:
#      close: true